
  homeareainfo:
    image: "homeareainfo"
    container_name: "homeareainfo"
    environment:
      - MAPBOX_ACCESS_TOKEN
      - TRAVELTIME_API_KEY
      - TRAVELTIME_APP_ID
      - GMAPS_API_KEY
      - HOMEAREA_DEBUG
    volumes:
      - /tmp/hah-datasets:/app/datasets
      - /tmp/hah-caches:/app/caches
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`homearea.beveradb.com`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=mytlschallenge"


