---
version: "2"
services:
  rutorrent:
    image: linuxserver/rutorrent:latest
    container_name: rutorrent
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/andrew/personal-vps-config/lon.beveradb.com/rutorrent-config:/config
      - /home/andrew/torrents:/downloads
    ports:
      - 80:80
      - 443:443
      - 5000:5000
      - 51413:51413
      - 6881:6881/udp
    restart: unless-stopped
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - /home/andrew/personal-vps-config/lon.beveradb.com/rutorrent-config/certbot/conf:/etc/letsencrypt
      - /home/andrew/personal-vps-config/lon.beveradb.com/rutorrent-config/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

